### PR TITLE
[7.x] Update blueprints.md

### PR DESCRIPTION
**Pull request by sjclark**
Fix awkward text 😬

### CODE REVIEW

**Review by duncanmcclean — APPROVED** [review]
Thanks!

**Comment by robdekort** [comment]
> Fix awkward text 😬

You're awkward!

**Comment by sjclark** [comment]
> > Fix awkward text 😬
> 
> You're awkward!

Screenshot 2024-07-06 at 8 38 41 pm

**Comment by robdekort** [comment]
lol

**Pull request merged**
