### PR TITLE
[7.x] Fix HasMany in revisions

### PR DESCRIPTION
**Pull request by edalzell**
If you have a HasMany field in the resource that is set up for revisions, it won't save properly when you publish, unless that field is filtered out.

You get this:

```
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updates' in 'field list' at /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:592)
[stacktrace]
#0 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(592): PDO->prepare('update `orphans...')
#1 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(800): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('update `orphans...', Array)
#2 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback('update `orphans...', Array, Object(Closure))
#3 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(584): Illuminate\\Database\\Connection->run('update `orphans...', Array, Object(Closure))
#4 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(536): Illuminate\\Database\\Connection->affectingStatement('update `orphans...', Array)
#5 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3722): Illuminate\\Database\\Connection->update('update `orphans...', Array)
#6 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1104): Illuminate\\Database\\Query\\Builder->update(Object(Illuminate\\Support\\Collection))
#7 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1218): Illuminate\\Database\\Eloquent\\Builder->update(Array)
#8 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1135): Illuminate\\Database\\Eloquent\\Model->performUpdate(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Revisions/Revisable.php(84): Illuminate\\Database\\Eloquent\\Model->save()
#10 /Users/erin/Development/runway/src/Traits/HasRunwayResource.php(241): App\\Models\\Orphan->publishWorkingCopy(Array)
#11 /Users/erin/Development/runway/src/Http/Controllers/CP/PublishedModelsController.php(21): App\\Models\\Orphan->publish(Array)
```

The SQL is:
```sql
update
  `orphans`
set
  `published` = 1,
  `story` = '[{\"type\":\"paragraph\",\"attrs\":{\"class\":null},\"content\":[{\"type\":\"text\",\"text\":\"Mohammed is a sweet boy. He was born in Dhaka city. He lost his father in 2012. Mohammed is attending school and doing great with his classes. His favorite subject is English language. He enjoys some of his free time listening to Music or playing cricket with his friends. Mohammed\'s dream is to become a doctor in the future.\"}]}]',
  `profile` = '{\"benefits\":[\"healthcare\",\"shelter\"],\"guardian\":null,\"birth_city\":null,\"report_card\":null,\"school_name\":null,\"school_grade\":null,\"benefit_other\":null,\"father_status\":null,\"mother_status\":null,\"school_address\":null,\"school_why_not\":null,\"interview_happy\":null,\"living_location\":null,\"school_attending\":false,\"school_religious\":null,\"birth_certificate\":\"sponsor-an-orphan\\/birth-certificates\\/0038-iden-c.pdf\",\"father_occupation\":null,\"fathers_full_name\":null,\"guardians_address\":null,\"interview_hobbies\":\"asdf\",\"medical_illnesses\":null,\"mother_occupation\":null,\"mothers_full_name\":null,\"orphanage_address\":null,\"guardians_relation\":null,\"medical_treatments\":null,\"number_of_siblings\":null,\"school_performance\":null,\"father_passing_date\":null,\"guardians_full_name\":null,\"mother_passing_date\":null,\"father_passing_cause\":null,\"mother_passing_cause\":null,\"guardians_phone_number\":null,\"interview_future_dreams\":\"sadf\",\"school_favorite_subject\":null,\"father_death_certificate\":null,\"interview_favorite_sport\":null,\"mother_death_certificate\":null}',
  `created_at` = '2021-11-10 00:00:00',
  `updates` = null,
  `orphans`.`updated_at` = '2024-07-05 10:20:07'
where
  `id` = 683
```

@duncanmcclean I attempted to get tests going for this and ran into some problems and I ran out of time to get them going. I can revisit in a bit, but his change finally makes revisions fully work for us.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
> If you have a HasMany field in the resource that is set up for revisions, it won't save properly unless you filter out that field.

When you say "it won't save properly unless you filter out that field", what do you mean? Which bit doesn't get saved properly - is no revision created, is the HasMany field's value incorrect in the revision?

**Comment by edalzell** [comment]
> When you say "it won't save properly unless you filter out that field", what do you mean? Which bit doesn't get saved properly - is no revision created, is the HasMany field's value incorrect in the revision?

I updated my description, sorry for the lousy report.

**Comment by duncanmcclean** [comment]
Thanks!

When did you hit that error - when you saved the working copy or when you published the model?

**Comment by edalzell** [comment]
> Thanks!
> 
> When did you hit that error - when you saved the working copy or when you published the model?

Only when you publish, because that's when it tries to write to the DB

**Comment by duncanmcclean** [comment]
I haven't had a chance to test this yet, but if you add/remove models in the revision, do those updates actually happen when the revision is published?

**Comment by duncanmcclean** [comment]
Thanks for the pull request!

However, after some testing, it seems like there was more to the Has Many fieldtype not working w/ revisions than just an error when publishing.

I've addressed those issues in #556.

**Pull request closed without merging**
